language: rust

os:
  - linux
  - windows
  - osx

rust:
  - nightly
  - stable

before_script:
  - if [ $TRAVIS_RUST_VERSION == "nightly" ]; then rustup component add rust-src --target=aarch64-uwp-windows-msvc; fi
  - if [ $TRAVIS_RUST_VERSION == "stable" ]; then rustup component add rustfmt; fi

script:
  - if [ $TRAVIS_RUST_VERSION == "stable" ]; then cargo fmt -- --check; fi
  - cargo build
  - if [ $TRAVIS_RUST_VERSION == "nightly" ]; then cargo build -Z build-std --target=aarch64-uwp-windows-msvc; fi
